### ISSUE TITLE
stratomex  duplicate columns

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/caleydo_clue#26] opened 2015-11-26 20:48 UTC
some columns aren't removed or appear twice

**Comment by gillhofer** [comment] 2016-06-01 13:15
I may have found a similar one. 

Create a new graph --> add a column --> add another column --> switch order of columns --> go to Start state -> go to last state. ---> you now have 3 columns.

**Comment by mstreit** [comment] 2016-06-01 13:20
I can confirm this. The problem is caused by switching to the start state.

**Comment by mstreit** [comment] 2016-09-12 14:16
Didn't see the problem since the fix attempt by @sgratzl. Seems to be solved. Closing issue.

**Closed by mstreit** 2016-09-12 14:16 UTC
Labels: BLOCKER
